spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-kafka?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
